# Generated by Django 3.2.4 on 2021-06-04 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, default=utils.helpers.create_short_uuid, editable=False, max_length=50, unique=True, verbose_name='UID')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('type', models.CharField(blank=True, choices=[('text', 'Text'), ('image', 'Image'), ('song', 'Song')], default='text', max_length=10, null=True, verbose_name='Type')),
                ('text', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Text')),
                ('song_url', models.CharField(blank=True, help_text='Add song url', max_length=250, null=True, verbose_name='Song')),
                ('image_url', models.CharField(blank=True, help_text='Add image url', max_length=250, null=True, verbose_name='Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ('-created',),
            },
        ),
    ]
